travel_anno_car:
    resource: "@TravelCarBundle/Controller/"
    prefix:   /{_locale}
    defaults:
        _locale: fr
    requirements:
        _locale: en|fr
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"