travel_car:
    resource: "@TravelCarBundle/Controller/"
    prefix:   /{_locale}
    defaults:
        _locale: fr
    requirements:
        _locale: en|fr
    type: annotation


# User root
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"