travel_car:
    resource: "@TravelCarBundle/Controller/"
    prefix:   /{_locale}
    defaults:
        _locale: fr
    requirements:
        _locale: en|fr
    type: annotation

travel_car_default:
    resource: "@TravelCarBundle/Controller/"
    type: annotation

# User root
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}
    defaults:
        _locale: fr
    requirements:
        _locale: en|fr

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
