# User root
travelCar_profile:
    resource: "@TravelCarBundle/Resources/config/routing/profile.yml"

# User root
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
    path:     /
    defaults: { _controller: TravelCarBundle:TravelCar:home }

# Annonce root

searchTreatment_adverts:
    path:     search/adverts/{page}/{numberPerPage}
    defaults:
        _controller: TravelCarBundle:Advert:searchTreatment
        page: 1
        numberPerPage: 5
    requirements:
        page: \d+
        numberPerPage: \d+


    
renderModifiyForm_advert:
    path:     adverts/formModify
    defaults: { _controller: TravelCarBundle:Advert:renderModifyForm }
    
add_advert:
    path:     adverts/add
    defaults: { _controller: TravelCarBundle:Advert:add }


view_advert:
    path: /view/{id}
    defaults:
        _controller: TravelCarBundle:Advert:view
    requirements:
        id: \d+
        
modify_advert:
    path:     adverts/modify/{id}
    defaults: { _controller: TravelCarBundle:Advert:modify }
    requirements:
        id: \d+
        
remove_advert:
    path: adverts/remove/{id}
    defaults: {_controller: TravelCarBundle:Advert:remove }
    requirements:
        id: \d+
        
# Reservation root
add_reservation:
    path:     reservations/add
    defaults: { _controller: TravelCarBundle:Reservation:add }
    
remove_reservation:
    path: reservations/remove/{advertId}
    defaults: {_controller: TravelCarBundle:Reservation:remove }
    requirements:
        advertId: \d+
        
# Post root
view_posts:
    path: posts/view/{advertId}
    defaults: {_controller: TravelCarBundle:Post:view }
    requirements:
        advertId: \d+
        
add_post:
    path: posts/add/{advertId}
    defaults: {_controller: TravelCarBundle:Post:add }
    requirements:
        advertId: \d+