# User root
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
    path:     /
    defaults: { _controller: TravelCarBundle:TravelCar:home }

# Annonce root

add_advert:
    path:     advert/add
    defaults: { _controller: TravelCarBundle:Advert:add }


view_advert:
    path: /view/{id}
    defaults:
        _controller: TravelCarBundle:Advert:view
    requirements:
        id: \d+

view_adverts:
    path: /adverts/{departureCity}/{cityOfArrival}/{departureDate}/{page}/{numberPerPage}
    defaults:
        _controller: TravelCarBundle:Advert:viewAdverts
        page: 1
        numberPerPage: 5
        departureCity: ''
        cityOfArrival: ''
        departureDate: ''
    requirements:
        page: \d*
        numberPerPage: \d*
        
# Reservation root