parameters:
    url: "http://www.lemonde.fr/m-actu/rss_full.xml"

services:
    travel_car_load_rss:
        class: TravelCarBundle\Service\GestionRSS
        arguments: ["%url%", "@logger"]

    travel_car_locale_listener:
        class: TravelCarBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
          - { name: kernel.event_subscriber }

    travel_car_style_user:
            class: TravelCarBundle\Service\StyleUser

    travel_car_login_listener:
        class: TravelCarBundle\EventListener\LoginListener
        arguments: ["@travel_car_style_user", "@session"]
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: onAuthenticationSuccess }