<?php

namespace TravelCarBundle\Entity\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByMatchAnnonces($departureCity, $cityOfArrival, $departureDate, $page, $numberPerPage){
        
        $queryBuilder = $this->createQueryBuilder('a');
        $departureDate = $departureDate->modify('-1 day');
        
        $queryBuilder->where('a.departureCity like :departureCity')
                ->setParameter('departureCity', $departureCity)
                ->andWhere('a.cityOfArrival like :cityOfArrival')
                ->setParameter('cityOfArrival', $cityOfArrival)
                ->andWhere('a.departureDate > :departureDate')
                ->setParameter('departureDate', $departureDate)
                ->orderBy('a.departureDate', 'ASC');  
        
        $adverts = $queryBuilder->getQuery();
        
        $adverts->setFirstResult(($page-1)*$numberPerPage)
                ->setMaxResults($numberPerPage);
        
        return new Paginator($adverts, true);     
    }
}
