<?php

namespace TravelCarBundle\Entity\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    /*public function findByUser($user, $page, $numberPerPage)
    {
        $queryBuilder = $this->createQueryBuilder('r');
        $queryBuilder->where('r.user = :user')
                ->setParameter('user', $user)
                ->orderBy('r.date', 'ASC');
        $reservations = $queryBuilder->getQuery();
        return new Paginator($reservations, true);
    }*/
}
